### ISSUE TITLE
大佬啊，这个翻译能支持自己定义的库吗？

### ISSUE THREAD

**Issue by jewer3330** [yanghuan/CSharp.lua#319]
大佬啊，这个翻译能支持自定义的库吗？比方说我在C夏普里调用了C嘎嘎，然后翻译出来能用吗？

**Comment by yanghuan** [comment]
源码翻译，需要C#源码------------------ 原始邮件 ------------------发件人: jun.zhao  <notifications@github.com>发送时间: 2020年9月23日 10:07收件人: yanghuan/CSharp.lua <CSharp.lua@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[yanghuan/CSharp.lua] 大佬啊，这个翻译能支持自己定义的库吗？ (#319)
大佬啊，这个翻译能支持自定义的库吗？比方说我在C夏普里调用了C嘎嘎，然后翻译出来能用吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yanghuan/CSharp.lua/issues/319",
"url": "https://github.com/yanghuan/CSharp.lua/issues/319",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
