### ISSUE TITLE
How to call external LUA methods

### ISSUE THREAD

**Issue by petterannerwall** [yanghuan/CSharp.lua#327]
Hey there!

I'm thinking of using this to write an addon for the game World of Warcraft which requires the language LUA but I'm more confident in C#. How would one go about to call external methods that exist in the World of Warcraft API? 

For example, simple the method `message("text")` would display a popup in-game displaying the message "text".  The rest of the LUA API could be seen here. https://wowwiki.fandom.com/wiki/World_of_Warcraft_API

Could you please point me in the right direction?

**Comment by Drake53** [comment]
There are two ways to do this:
https://github.com/yanghuan/CSharp.lua/wiki/attributes_en#csharpluatemplate
https://github.com/yanghuan/CSharp.lua/wiki/FAQ_en#7how-do-you-call-or-insert-lua-code-in-your-code

I personally prefer the first, for example here: https://github.com/Drake53/War3Api/blob/master/src/War3Api.Common/Common/Common.cs

**Comment by petterannerwall** [comment]
Thanks for the fast reply, just had the time to test this out myself, but i'm getting a error and i'm not sure but im guessing this is more related to WoW then LUA or this library but even the minial code below results in this error.

```
-- Generated by CSharp.lua Compiler
local System = System
System.namespace("csharp_addon", function (namespace)
 -- omitted code here.
end)
```
![image](https://user-images.githubusercontent.com/5909669/99192057-05619100-2771-11eb-810a-f0f2d8782fdf.png)

**Comment by yanghuan** [comment]
thanks Drake53

**Comment by petterannerwall** [comment]
Thanks for the answer, didn't have time to look into this until just now but apparently, the WoW implementation of LUA doesn't have all the keywords such as `require` for example. This, unfortunately, breaks stuff so it seems I can't use this library

**Comment by yanghuan** [comment]
you can use argument with "-include" it output single file

**Comment by petterannerwall** [comment]
Huh, how did i miss that. Thanks for the response. Sadly I still get errors and I don't really understand why.  This is the error in getting and below are the generated LUA code and after that the C# code. 

I understand that this is probably out of scope for this project so just let me know and I'll continue looking elsewhere for help.

```
Message: Interface\AddOns\CSharp\Program.lua:3: attempt to index local 'System' (a nil value)
Time: Wed Nov 18 12:30:01 2020
Count: 1
Stack: Interface\AddOns\CSharp\Program.lua:3: attempt to index local 'System' (a nil value)
[string "@Interface\AddOns\CSharp\Program.lua"]:3: in main chunk

Locals: System = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'System' (a nil value)"

```

```
-- Generated by CSharp.lua Compiler
local System = System
System.namespace("csharp_addon", function (namespace)
  namespace.class("Program", function (namespace)
    local Main
    Main = function (args)
      message("Hello World")
    end
    return {
      Main = Main
    }
  end)
end)

```

```
namespace csharp_addon
{
    class Program
    {
        static void Main(string[] args)
        {
            WoWAPI.Message("Hello World");
        }
    }   
    public static class WoWAPI
    {
        /// @CSharpLua.Template = "message({0})"
        public static extern string Message(string message);
    }

}

```

**Comment by Drake53** [comment]
CSharpLua has its own lua library that is required to run the generated code. This library is not added, that's why you're getting the error that 'System' is null. You can find it the library here: https://github.com/yanghuan/CSharp.lua/tree/master/CSharp.lua/CoreSystem.Lua/CoreSystem

I'm not 100% sure how to make sure the coresystem files are added to the top of your .lua file, since I have my own fork of CSharpLua with a bunch of changes. If you can't figure it out, you can check out my fork to see how I do it (entry point into the library is the CompileSingleFile method): https://github.com/Drake53/CSharp.lua/blob/master/CSharp.lua/Compiler.cs

**Comment by petterannerwall** [comment]
@Drake53 Thanks for being so helpful, will reply when I had the time to check it out. Thanks a bunch already!

**Comment by Cheatoid** [comment]
@Drake53 Could you enable issues since you maintain your own fork please?
I have one issue with your current version, the `MetaResources` doesn't seem to exist:
https://github.com/Drake53/CSharp.lua/blob/12000c9ed64a6f925b4650c355d318a50c559142/CSharp.lua/XmlMetaProvider.cs#L269
![image](https://user-images.githubusercontent.com/13347909/103011409-279dba00-453a-11eb-9ca6-9dfb1aaf6b78.png)

**Comment by Drake53** [comment]
@Cheatoid issues are enabled now.
The error is caused because I don't have the file generated by MetaResources.resx added to source control. If you rightclick that file and generate it (I think the context menu item is called 'Run Custom Tool') it should work.
